
conference = [
'Big Ten' 
,'Big 12' 
,'MVC' 
,'Sun Belt' 
,'WAC' 
,'Southern' 
,'Pac-12' 
,'SEC' 
,'WCC'
,'OVC' 
,'MWC' 
,'ACC' 
,'A-10' 
,'AAC' 
,'Big West' 
,'MAAC' 
,'Big Sky' 
,'MEAC' 
,'Ivy'
,'Horizon' 
,'AEC' 
,'Big South' 
,'Summit'
,'SWAC' 
,'NEC' 
,'CAA' 
,'Southland' 
,'MAC'
,'A-Sun' 
,'Big East' 
,'CUSA' 
,'Patriot' 
,'Ind'
]

teams = {'Big Ten': {'Purdue': 'Purdue',
  'Illinois': 'Illinois',
  'Northwestern': 'Northwestern',
  'Ohio State': 'Ohio State',
  'Wisconsin': 'Wisconsin',
  'Michigan State': 'Michigan State',
  'Minnesota': 'Minnesota',
  'Penn State': 'Penn State',
  'Michigan': 'Michigan',
  'Indiana': 'Indiana',
  'Rutgers': 'Rutgers',
  'Iowa': 'Iowa',
  'Maryland': 'Maryland',
  'Nebraska': 'Nebraska'},
 'Big 12': {'Houston': 'Houston',
  'Iowa State': 'Iowa State',
  'Brigham Young': 'Brigham Young',
  'Kansas': 'Kansas',
  'TCU': 'TCU',
  'Kansas State': 'Kansas State',
  'UCF': 'UCF',
  'Oklahoma State': 'Oklahoma State',
  'West Virginia': 'West Virginia',
  'Baylor': 'Baylor',
  'Cincinnati': 'Cincinnati',
  'Texas Tech': 'Texas Tech',
  'Texas': 'Texas',
  'Oklahoma': 'Oklahoma'},
 'MVC': {'Indiana State': 'Indiana State',
  'Drake': 'Drake',
  'Bradley': 'Bradley',
  'Belmont': 'Belmont',
  'Southern Illinois': 'Southern Illinois',
  'Evansville': 'Evansville',
  'Missouri State': 'Missouri State',
  'Illinois State': 'Illinois State',
  'Illinois–Chicago': 'Illinois–Chicago',
  'Murray State': 'Murray State',
  'Valparaiso': 'Valparaiso',
  'Northern Iowa': 'Northern Iowa'},
 'Sun Belt': {'James Madison': 'James Madison',
  'Arkansas State': 'Arkansas State',
  'Troy': 'Troy',
  'Louisiana': 'Louisiana',
  'Texas State': 'Texas State',
  'South Alabama': 'South Alabama',
  'Southern Mississippi': 'Southern Mississippi',
  'Georgia State': 'Georgia State',
  'Marshall': 'Marshall',
  'Louisiana–Monroe': 'Louisiana–Monroe',
  'Coastal Carolina': 'Coastal Carolina',
  'Old Dominion': 'Old Dominion',
  'Georgia Southern': 'Georgia Southern',
  'Appalachian State': 'Appalachian State'},
 'WAC': {'Grand Canyon': 'Grand Canyon',
  'Tarleton State': 'Tarleton State',
  'Seattle': 'Seattle',
  'UT Arlington': 'UT Arlington',
  'Stephen F. Austin': 'Stephen F. Austin',
  'Abilene Christian': 'Abilene Christian',
  'California Baptist': 'California Baptist',
  'Utah Valley': 'Utah Valley',
  'Utah Tech': 'Utah Tech',
  'Southern Utah': 'Southern Utah',
  'Texas–Rio Grande Valley': 'Texas–Rio Grande Valley'},
 'Southern': {'Samford': 'Samford',
  'Western Carolina': 'Western Carolina',
  'Chattanooga': 'Chattanooga',
  'UNC Greensboro': 'UNC Greensboro',
  'Furman': 'Furman',
  'Wofford': 'Wofford',
  'Mercer': 'Mercer',
  'The Citadel': 'The Citadel',
  'VMI': 'VMI',
  'East Tennessee State': 'East Tennessee State'},
 'Pac-12': {'Arizona': 'Arizona',
  'Colorado': 'Colorado',
  'Washington': 'Washington',
  'UCLA': 'UCLA',
  'Southern California': 'Southern California',
  'Stanford': 'Stanford',
  'California': 'California',
  'Oregon State': 'Oregon State',
  'Washington State': 'Washington State',
  'Oregon': 'Oregon',
  'Utah': 'Utah',
  'Arizona State': 'Arizona State'},
 'SEC': {'Auburn': 'Auburn',
  'South Carolina': 'South Carolina',
  'Kentucky': 'Kentucky',
  'Mississippi State': 'Mississippi State',
  'Texas A&M': 'Texas A&M',
  'Georgia': 'Georgia',
  'Ole Miss': 'Ole Miss',
  'Arkansas': 'Arkansas',
  'Vanderbilt': 'Vanderbilt',
  'Missouri': 'Missouri',
  'Tennessee': 'Tennessee',
  'Alabama': 'Alabama',
  'Florida': 'Florida',
  'Louisiana State': 'Louisiana State'},
 'WCC': {'Gonzaga': 'Gonzaga',
  'San Francisco': 'San Francisco',
  'Santa Clara': 'Santa Clara',
  'San Diego': 'San Diego',
  'Pepperdine': 'Pepperdine',
  'Loyola Marymount': 'Loyola Marymount',
  'Portland': 'Portland',
  'Pacific': 'Pacific',
  "St. Mary's (CA)": "St. Mary's (CA)"},
 'OVC': {'Morehead State': 'Morehead State',
  'Little Rock': 'Little Rock',
  'UT Martin': 'UT Martin',
  'Tennessee State': 'Tennessee State',
  'SIU Edwardsville': 'SIU Edwardsville',
  'Eastern Illinois': 'Eastern Illinois',
  'Tennessee Tech': 'Tennessee Tech',
  'Lindenwood': 'Lindenwood',
  'Southeast Missouri State': 'Southeast Missouri State',
  'Southern Indiana': 'Southern Indiana',
  'Western Illinois': 'Western Illinois'},
 'MWC': {'Nevada': 'Nevada',
  'New Mexico': 'New Mexico',
  'Boise State': 'Boise State',
  'UNLV': 'UNLV',
  'Wyoming': 'Wyoming',
  'Fresno State': 'Fresno State',
  'Air Force': 'Air Force',
  'San Jose State': 'San Jose State',
  'Utah State': 'Utah State',
  'San Diego State': 'San Diego State',
  'Colorado State': 'Colorado State'},
 'ACC': {'NC State': 'NC State',
  'Clemson': 'Clemson',
  'Virginia': 'Virginia',
  'Pittsburgh': 'Pittsburgh',
  'Syracuse': 'Syracuse',
  'Virginia Tech': 'Virginia Tech',
  'Miami (FL)': 'Miami (FL)',
  'Georgia Tech': 'Georgia Tech',
  'Notre Dame': 'Notre Dame',
  'Louisville': 'Louisville',
  'North Carolina': 'North Carolina',
  'Duke': 'Duke',
  'Wake Forest': 'Wake Forest',
  'Boston College': 'Boston College',
  'Florida State': 'Florida State'},
 'A-10': {'Dayton': 'Dayton',
  'Duquesne': 'Duquesne',
  'VCU': 'VCU',
  'Richmond': 'Richmond',
  "Saint Joseph's": "Saint Joseph's",
  'Massachusetts': 'Massachusetts',
  'St. Bonaventure': 'St. Bonaventure',
  'La Salle': 'La Salle',
  'George Washington': 'George Washington',
  'Fordham': 'Fordham',
  'Saint Louis': 'Saint Louis',
  'Rhode Island': 'Rhode Island',
  'Davidson': 'Davidson',
  'Loyola Chicago': 'Loyola Chicago',
  'George Mason': 'George Mason'},
 'AAC': {'South Florida': 'South Florida',
  'Memphis': 'Memphis',
  'Charlotte': 'Charlotte',
  'Temple': 'Temple',
  'Tulsa': 'Tulsa',
  'East Carolina': 'East Carolina',
  'Wichita State': 'Wichita State',
  'Tulane': 'Tulane',
  'Rice': 'Rice',
  'UTSA': 'UTSA',
  'Florida Atlantic': 'Florida Atlantic',
  'SMU': 'SMU',
  'UAB': 'UAB',
  'North Texas': 'North Texas'},
 'Big West': {'UC Irvine': 'UC Irvine',
  'Hawaii': 'Hawaii',
  'Cal State Northridge': 'Cal State Northridge',
  'UC Riverside': 'UC Riverside',
  'UC Santa Barbara': 'UC Santa Barbara',
  'Cal State Fullerton': 'Cal State Fullerton',
  'Cal State Bakersfield': 'Cal State Bakersfield',
  'Cal Poly': 'Cal Poly',
  'UC San Diego': 'UC San Diego',
  'Long Beach State': 'Long Beach State',
  'UC Davis': 'UC Davis'},
 'MAAC': {'Fairfield': 'Fairfield',
  "Saint Peter's": "Saint Peter's",
  'Marist': 'Marist',
  'Iona': 'Iona',
  'Niagara': 'Niagara',
  'Rider': 'Rider',
  'Canisius': 'Canisius',
  "Mount St. Mary's": "Mount St. Mary's",
  'Manhattan': 'Manhattan',
  'Siena': 'Siena',
  'Quinnipiac': 'Quinnipiac'},
 'Big Sky': {'Montana': 'Montana',
  'Eastern Washington': 'Eastern Washington',
  'Northern Colorado': 'Northern Colorado',
  'Montana State': 'Montana State',
  'Portland State': 'Portland State',
  'Idaho State': 'Idaho State',
  'Northern Arizona': 'Northern Arizona',
  'Idaho': 'Idaho',
  'Sacramento State': 'Sacramento State',
  'Weber State': 'Weber State'},
 'MEAC': {'Norfolk State': 'Norfolk State',
  'Howard': 'Howard',
  'North Carolina Central': 'North Carolina Central',
  'Delaware State': 'Delaware State',
  'South Carolina State': 'South Carolina State',
  'Morgan State': 'Morgan State',
  'Maryland Eastern Shore': 'Maryland Eastern Shore',
  'Coppin State': 'Coppin State'},
 'Ivy': {'Princeton': 'Princeton',
  'Yale': 'Yale',
  'Cornell': 'Cornell',
  'Harvard': 'Harvard',
  'Brown': 'Brown',
  'Dartmouth': 'Dartmouth',
  'Pennsylvania': 'Pennsylvania',
  'Columbia': 'Columbia'},
 'Horizon': {'Purdue Fort Wayne': 'Purdue Fort Wayne',
  'Youngstown State': 'Youngstown State',
  'Cleveland State': 'Cleveland State',
  'Robert Morris': 'Robert Morris',
  'IUPUI': 'IUPUI',
  'Detroit Mercy': 'Detroit Mercy',
  'Oakland': 'Oakland',
  'Milwaukee': 'Milwaukee',
  'Green Bay': 'Green Bay',
  'Northern Kentucky': 'Northern Kentucky',
  'Wright State': 'Wright State'},
 'AEC': {'UMass Lowell': 'UMass Lowell',
  'Bryant': 'Bryant',
  'New Hampshire': 'New Hampshire',
  'Binghamton': 'Binghamton',
  'Maine': 'Maine',
  'Albany (NY)': 'Albany (NY)',
  'UMBC': 'UMBC',
  'NJIT': 'NJIT',
  'Vermont': 'Vermont'},
 'Big South': {'UNC Asheville': 'UNC Asheville',
  'Longwood': 'Longwood',
  'Winthrop': 'Winthrop',
  'Radford': 'Radford',
  'Presbyterian': 'Presbyterian',
  'Charleston Southern': 'Charleston Southern',
  'USC Upstate': 'USC Upstate',
  'High Point': 'High Point',
  'Gardner-Webb': 'Gardner-Webb'},
 'Summit': {'South Dakota State': 'South Dakota State',
  'St. Thomas': 'St. Thomas',
  'North Dakota': 'North Dakota',
  'Denver': 'Denver',
  'Kansas City': 'Kansas City',
  'Omaha': 'Omaha',
  'North Dakota State': 'North Dakota State',
  'Oral Roberts': 'Oral Roberts',
  'South Dakota': 'South Dakota'},
 'SWAC': {'Grambling State': 'Grambling State',
  'Southern': 'Southern',
  'Bethune-Cookman': 'Bethune-Cookman',
  'Texas Southern': 'Texas Southern',
  'Jackson State': 'Jackson State',
  'Alcorn State': 'Alcorn State',
  'Alabama State': 'Alabama State',
  'Arkansas–Pine Bluff': 'Arkansas–Pine Bluff',
  'Alabama A&M': 'Alabama A&M',
  'Prairie View A&M': 'Prairie View A&M',
  'Florida A&M': 'Florida A&M',
  'Mississippi Valley State': 'Mississippi Valley State'},
 'NEC': {'Merrimack': 'Merrimack',
  'Central Connecticut State': 'Central Connecticut State',
  'Sacred Heart': 'Sacred Heart',
  'FDU': 'FDU',
  'Le Moyne': 'Le Moyne',
  'Saint Francis (PA)': 'Saint Francis (PA)',
  'LIU': 'LIU',
  'Stonehill': 'Stonehill',
  'Wagner': 'Wagner'},
 'CAA': {'UNC Wilmington': 'UNC Wilmington',
  'Drexel': 'Drexel',
  'Hofstra': 'Hofstra',
  'Stony Brook': 'Stony Brook',
  'Towson': 'Towson',
  'Delaware': 'Delaware',
  'Monmouth': 'Monmouth',
  'Campbell': 'Campbell',
  'Elon': 'Elon',
  'Northeastern': 'Northeastern',
  'Hampton': 'Hampton',
  'North Carolina A&T': 'North Carolina A&T',
  'William & Mary': 'William & Mary',
  'College of Charleston': 'College of Charleston'},
 'Southland': {'Texas A&M–Corpus Christi': 'Texas A&M–Corpus Christi',
  'Nicholls State': 'Nicholls State',
  'Lamar': 'Lamar',
  'Southeastern Louisiana': 'Southeastern Louisiana',
  'Texas A&M–Commerce': 'Texas A&M–Commerce',
  'New Orleans': 'New Orleans',
  'Northwestern State': 'Northwestern State',
  'Incarnate Word': 'Incarnate Word',
  'Houston Christian': 'Houston Christian',
  'McNeese State': 'McNeese State'},
 'MAC': {'Bowling Green': 'Bowling Green',
  'Toledo': 'Toledo',
  'Central Michigan': 'Central Michigan',
  'Kent State': 'Kent State',
  'Ball State': 'Ball State',
  'Miami (OH)': 'Miami (OH)',
  'Eastern Michigan': 'Eastern Michigan',
  'Western Michigan': 'Western Michigan',
  'Northern Illinois': 'Northern Illinois',
  'Buffalo': 'Buffalo',
  'Ohio': 'Ohio',
  'Akron': 'Akron'},
 'A-Sun': {'Lipscomb': 'Lipscomb',
  'Eastern Kentucky': 'Eastern Kentucky',
  'Jacksonville': 'Jacksonville',
  'North Florida': 'North Florida',
  'Kennesaw State': 'Kennesaw State',
  'Florida Gulf Coast': 'Florida Gulf Coast',
  'Queens (NC)': 'Queens (NC)',
  'Central Arkansas': 'Central Arkansas',
  'Bellarmine': 'Bellarmine',
  'Stetson': 'Stetson',
  'Austin Peay': 'Austin Peay',
  'North Alabama': 'North Alabama'},
 'Big East': {"St. John's (NY)": "St. John's (NY)",
  'Butler': 'Butler',
  'Villanova': 'Villanova',
  'Georgetown': 'Georgetown',
  'DePaul': 'DePaul',
  'Providence': 'Providence',
  'Xavier': 'Xavier',
  'Connecticut': 'Connecticut',
  'Marquette': 'Marquette',
  'Creighton': 'Creighton',
  'Seton Hall': 'Seton Hall'},
 'CUSA': {'Liberty': 'Liberty',
  'UTEP': 'UTEP',
  'Jacksonville State': 'Jacksonville State',
  'Middle Tennessee': 'Middle Tennessee',
  'New Mexico State': 'New Mexico State',
  'Florida International': 'Florida International',
  'Louisiana Tech': 'Louisiana Tech',
  'Western Kentucky': 'Western Kentucky',
  'Sam Houston State': 'Sam Houston State'},
 'Patriot': {'American': 'American',
  'Boston University': 'Boston University',
  'Bucknell': 'Bucknell',
  'Lehigh': 'Lehigh',
  'Navy': 'Navy',
  'Lafayette': 'Lafayette',
  'Army': 'Army',
  'Holy Cross': 'Holy Cross',
  'Loyola (MD)': 'Loyola (MD)',
  'Colgate': 'Colgate'},
 'Ind': {'Chicago State': 'Chicago State'}}